# Generated by Django 4.2.2 on 2023-06-06 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMaster",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=500,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="User ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("mobile", models.CharField(blank=True, max_length=11)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("otp", models.IntegerField(default=False, editable=False)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
