# Generated by Django 4.2 on 2023-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_otp_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermaster",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
